### ISSUE TITLE
Add attractive background

### ISSUE THREAD

**Issue by saurabhprasadsah** [alexiscenriquez/temperature-converter#1]
add logical background on  your project.......

**Comment by alexiscenriquez** [comment]
If I may ask, what sort of background? Would a solid color be preferable

**Comment by saurabhprasadsah** [comment]
Yes, only one color would be good.

**Comment by saurabhprasadsah** [comment]
one color..

**Comment by alexiscenriquez** [comment]
It is though. The background color is #D96704

**Comment by saurabhprasadsah** [comment]
its gud..
